package com.example.retrofit;

import com.google.gson.annotations.SerializedName;

/* this class contain json variable and its value
 * number of variable in thus class must be same name as json
 * or we can use my choice but use a notation for this *********/
public class Post {
    private int userId;

    // Id will generated by server
    // GSON will default set it null for this we have to set 'int' to Integer
    private Integer id;

    private String title;

    /*we can use my choice name but use a notation for this*/
    // It is a GSON properties
    @SerializedName("body")
    private String message;

    public Post(int userId, String title, String message) {
        this.userId = userId;
        this.title = title;
        this.message = message;
    }

    public int getUserId() {
        return userId;
    }

    public Integer getId() {
        return id;
    }

    public String getTitle() {
        return title;
    }

    public String getMessage() {
        return message;
    }
}
